"use strict";
const assert = require("assert");
const fs = require("fs");
const path = require("path");
const {
  PAGES,
  pageFor,
  fileFor,
  publicSnapshot,
  handlePublicRequest,
  createPublicFetch,
} = require("../electron/netie/host-serve");
const { createCoordinator } = require("../electron/netie/coordinator");

const HOST = path.join(__dirname, "..", "host");

let pass = 0;
const fails = [];
function test(name, fn) {
  const run = Promise.resolve().then(fn);
  return run
    .then(() => {
      pass += 1;
      console.log("PASS " + name);
    })
    .catch((err) => {
      fails.push(name);
      console.log("FAIL " + name + " -- " + err.message);
    });
}

function readAsset(file) {
  const abs = path.resolve(HOST, file);
  if (!abs.startsWith(path.resolve(HOST) + path.sep) && abs !== path.resolve(HOST)) {
    return null;
  }
  if (!fs.existsSync(abs)) return null;
  return fs.readFileSync(abs);
}

(async () => {
  await test("public pages match the coordinator map", () => {
    const c = createCoordinator();
    assert.deepStrictEqual(c.PAGES, PAGES);
    assert.strictEqual(pageFor("/today/"), "today");
    assert.strictEqual(pageFor("/meeting"), "meeting");
    assert.strictEqual(pageFor("/teach"), "teach");
    assert.strictEqual(pageFor("/security"), "security");
    assert.strictEqual(pageFor("/document"), "document");
    assert.strictEqual(pageFor("/inbox"), "inbox");
    assert.strictEqual(pageFor("/overlay"), null);
    assert.strictEqual(fileFor("/overlay"), "overlay.html");
    assert.strictEqual(pageFor("/secret"), null);
  });

  await test("public /api/state is a local-first shell with empty lanes", () => {
    const routed = handlePublicRequest({ method: "GET", pathname: "/api/state" });
    assert.strictEqual(routed.status, 200);
    const body = JSON.parse(routed.body);
    assert.strictEqual(body.localFirst, true);
    assert.strictEqual(body.coordinator, "http://127.0.0.1:18010");
    assert.strictEqual(body.lanes["pointer-act"], null);
    assert.strictEqual(body.lanes.cortex, null);
    assert.deepStrictEqual(body.drafts, []);
    assert.ok(/laptop/.test(body.reason));
    assert.strictEqual(body.exec, false);
    const snap = publicSnapshot();
    snap.lanes["pointer-act"] = { owner: "should-not-leak" };
    const again = JSON.parse(handlePublicRequest({ method: "GET", pathname: "/api/state" }).body);
    assert.strictEqual(again.lanes["pointer-act"], null);
  });

  await test("public /mcp is refused", () => {
    const a = handlePublicRequest({ method: "POST", pathname: "/mcp" });
    assert.strictEqual(a.status, 404);
    assert.match(a.body, /127\.0\.0\.1/);
    const b = handlePublicRequest({ method: "GET", pathname: "/mcp/tools" });
    assert.strictEqual(b.status, 404);
  });

  await test("public workspace is a catalog with no runtime", async () => {
    const routed = handlePublicRequest({ method: "GET", pathname: "/api/workspace" });
    assert.strictEqual(routed.status, 200);
    const body = JSON.parse(routed.body);
    assert.strictEqual(body.localFirst, true);
    assert.strictEqual(body.exec, false);
    assert.deepStrictEqual(body.artifacts, []);
    assert.ok(body.desks.some((d) => d.id === "teach"));
    const exec = handlePublicRequest({ method: "POST", pathname: "/api/workspace/exec" });
    assert.strictEqual(exec.status, 404);
    const write = handlePublicRequest({ method: "POST", pathname: "/api/workspace" });
    assert.strictEqual(write.status, 404);
    const teachPost = handlePublicRequest({ method: "POST", pathname: "/api/teach" });
    assert.strictEqual(teachPost.status, 404);
    const meetingPost = handlePublicRequest({ method: "POST", pathname: "/api/meeting" });
    assert.strictEqual(meetingPost.status, 404);
    const askPost = handlePublicRequest({ method: "POST", pathname: "/api/ask" });
    assert.strictEqual(askPost.status, 404);
    const fetch = createPublicFetch(readAsset);
    const html = await fetch(new Request("https://host.netie.ai/workspace"));
    assert.strictEqual(html.status, 200);
    const page = await html.text();
    assert.match(page, /no runtime/i);
    assert.match(page, /Demo coworker/);
    assert.match(page, /id="desks"/);
    assert.match(page, /id="computer-dock"/);
    assert.match(page, /id="computer-run"/);
    const app = fs.readFileSync(path.join(HOST, "app.js"), "utf8");
    assert.match(app, /paintDesks/);
    assert.match(app, /isWorkspacePage/);
    assert.match(app, /paintComputerDock/);
    assert.match(app, /wireComputerRun/);
    assert.match(app, /\/api\/workspace\/exec/);
    assert.match(app, /docx-download/);
    assert.match(app, /\/api\/document\.docx/);
    assert.match(app, /eml-download/);
    assert.match(app, /\/api\/inbox\.eml/);
    assert.match(app, /report-download/);
    assert.match(app, /\/api\/security\.md/);
    assert.match(app, /\/workspace\?id=live-security/);
    assert.match(app, /act: false/);
    assert.match(app, /textContent/);
    assert.doesNotMatch(app, /innerHTML/);
    assert.match(app, /pollWhileLive/);
    assert.match(app, /ws\.exec/);
    assert.match(app, /openArtifact/);
    assert.match(app, /setFinishedDownloads/);
    assert.match(app, /Open in workspace/);
    assert.match(app, /\/workspace\?id=live-document/);
    assert.match(app, /\/workspace\?id=live-inbox/);
    assert.match(app, /paintLanes/);
    assert.match(app, /artifact-filter/);
    assert.match(page, /id="artifact-filter"/);
    const leak = handlePublicRequest({
      method: "GET",
      pathname: "/api/workspace",
      search: "?id=brief-1",
    });
    assert.strictEqual(leak.status, 404);
    assert.strictEqual(JSON.parse(leak.body).exec, false);
    assert.match(JSON.parse(leak.body).reason, /laptop/);
    const lanes = await fetch(new Request("https://host.netie.ai/lanes"));
    assert.match(await lanes.text(), /id="lanes"/);
    const skills = await fetch(new Request("https://host.netie.ai/skills"));
    assert.match(await skills.text(), /id="hits"/);
    assert.match(page, /id="artifact-body"/);
    assert.match(page, /id="artifact-chips"/);
    assert.match(page, /id="session"/);
    assert.match(page, /id="session-files"/);
    assert.match(page, /id="computer-files-kicker"/);
    assert.match(page, /session-grid/);
    assert.match(page, /Files on this computer/);
    assert.match(page, /id="session-md"/);
    assert.match(page, /id="session-copy"/);
    assert.match(page, /id="session-download"/);
    assert.match(page, /id="artifact-copy"/);
    assert.match(page, /id="artifact-download"/);
    assert.match(page, /id="docx-download"/);
    assert.match(page, /id="eml-download"/);
    assert.match(page, /id="report-download"/);
    assert.match(page, /id="open-file"/);
    assert.match(page, /id="open-file-kicker"/);
    assert.match(page, /id="open-file-tabs"/);
    assert.match(page, /workspace-catalog/);
    assert.match(page, /Open window/);
    assert.match(page, /open it as a window/);
    assert.match(page, /tabs on the open file/);
    assert.match(page, /generated \.docx/);
    assert.match(page, /security review/);
  });

  await test("public fetch serves /today and style.css from host/", async () => {
    const fetch = createPublicFetch(readAsset);
    const home = await fetch(new Request("https://host.netie.ai/"));
    assert.strictEqual(home.status, 200);
    const homeText = await home.text();
    assert.match(homeText, /Pointer coworker/);
    assert.doesNotMatch(homeText, /id="desks"/);
    assert.match(homeText, /id="rooms"/);
    assert.match(homeText, /room-dock/);
    assert.match(homeText, /This computer/);
    assert.match(homeText, /This display/);
    assert.match(homeText, /sample coworker/);
    assert.match(homeText, /Demo coworker/);
    assert.match(homeText, /id="stage"/);
    assert.match(homeText, /id="session"/);
    assert.match(homeText, /id="session-files"/);
    assert.match(homeText, /session-grid/);
    assert.match(homeText, /id="session-md"/);
    assert.match(homeText, /id="session-copy"/);
    assert.match(homeText, /id="session-download"/);
    assert.match(homeText, /id="brief"/);
    assert.doesNotMatch(homeText, /id="state"/);
    const html = await fetch(new Request("https://host.netie.ai/today"));
    assert.strictEqual(html.status, 200);
    const text = await html.text();
    assert.match(text, /host\.netie\.ai \/today/);
    assert.match(text, /id="brief"/);
    assert.match(text, /id="today-cue-web"/);
    assert.match(text, /id="today-chips"/);
    assert.match(text, /id="today-plate"/);
    assert.match(text, /id="events"/);
    const todayApi = handlePublicRequest({ method: "GET", pathname: "/api/today" });
    assert.strictEqual(todayApi.status, 200);
    const todayBody = JSON.parse(todayApi.body);
    assert.strictEqual(todayBody.localFirst, true);
    assert.strictEqual(todayBody.act, false);
    assert.strictEqual(todayBody.exec, false);
    assert.deepStrictEqual(todayBody.events, []);
    assert.deepStrictEqual(todayBody.chips, []);
    assert.deepStrictEqual(todayBody.plate, []);
    assert.match(todayBody.deliverable, /nothing yet/);
    assert.match(todayBody.deliverable, /P-06/);
    const app = fs.readFileSync(path.join(HOST, "app.js"), "utf8");
    assert.match(app, /paintBrief/);
    assert.match(app, /\/api\/today/);
    assert.match(app, /\/api\/meeting/);
    assert.match(app, /\/api\/teach/);
    assert.match(app, /\/api\/security/);
    assert.match(app, /\/api\/document/);
    assert.match(app, /\/api\/inbox/);
    assert.match(app, /\/api\/home/);
    assert.match(app, /paintRooms/);
    assert.match(app, /room-dock-tile/);
    assert.match(app, /paintFiledWindow/);
    assert.match(app, /paintStage/);
    assert.match(app, /paintSession/);
    assert.match(app, /paintChrome/);
    assert.match(app, /live-cue-bar/);
    assert.match(app, /host-ask/);
    assert.match(app, /postAsk/);
    assert.match(app, /\/api\/ask/);
    assert.match(app, /paintTodayChips/);
    assert.match(app, /paintDeskChips/);
    assert.match(app, /lastOpenId/);
    assert.match(app, /host-open/);
    assert.match(app, /workspaceQueryId/);
    assert.match(app, /replaceState/);
    assert.match(app, /sessionLinkHref/);
    assert.match(app, /paintSessionTile/);
    assert.match(app, /sessionTileKind/);
    assert.match(app, /session-tile/);
    assert.match(app, /\/workspace\?id=/);
    const paint = app.slice(app.indexOf("function paintSession"), app.indexOf("const roomsPage"));
    assert.match(paint, /session-md/);
    assert.match(paint, /mdEl.hidden = true/);
    assert.match(paint, /session-copy/);
    assert.match(paint, /session-download/);
    assert.match(paint, /textContent/);
    assert.match(app, /writeText/);
    assert.match(app, /createObjectURL/);
    assert.match(app, /\/api\/session\.zip/);
    assert.match(app, /pointer-session.zip/);
    assert.match(app, /pointer-session.md/);
    assert.match(app, /briefFileName/);
    assert.match(app, /artifact-copy/);
    assert.doesNotMatch(paint, /innerHTML/);
    assert.match(app, /Live session stays on the laptop/);
    assert.match(app, /paintTeachMap/);
    assert.match(app, /teachControlFace/);
    assert.match(app, /teach-map-control/);
    assert.match(app, /teach-map-screen/);
    assert.match(app, /p\.now && p\.cue/);
    assert.match(app, /wireTeachFrame/);
    assert.match(app, /wireTeachTap/);
    assert.match(app, /teach-map tap/);
    assert.match(app, /applyHomeTeach/);
    assert.match(app, /postTeachFrame/);
    assert.match(app, /teach-map/);
    assert.match(app, /teach-map-cue/);
    assert.match(app, /teach-map-mark/);
    assert.match(app, /teach-map-rail/);
    assert.match(app, /fill: "Sarah Chen"/);
    assert.match(app, /p\.now && p\.fill/);
    assert.match(app, /onTeachRailStep/);
    assert.match(app, /data-rail/);
    assert.match(app, /data-step/);
    assert.match(app, /teach-map-key/);
    assert.match(app, /teach-map-box then/);
    assert.match(app, /Draw another BOX to add a step/);
    assert.match(app, /Click the current BOX to Got it/);
    assert.match(app, /hitTeachBox/);
    assert.match(app, /i clicked/);
    assert.match(app, /teach-map-stroke/);
    assert.match(app, /paintTeachInk/);
    assert.match(app, /teach-map-ink/);
    assert.match(app, /teachActionLine/);
    assert.match(app, /speakTeachCue/);
    assert.match(app, /isDemoPage/);
    assert.match(app, /isDemoCatalog/);
    assert.match(app, /paintDemoIfPublic/);
    assert.match(app, /demoCatalogOn = true/);
    assert.match(app, /paintingDemo/);
    assert.match(app, /if \(demoCatalogOn\) return true/);
    assert.match(app, /if \(paintingDemo\) return false/);
    assert.match(app, /demoHome/);
    assert.match(app, /demoTeachStep > 0 \? "Sarah Chen" : "not sent"/);
    assert.match(app, /demoInboxSaved/);
    assert.match(app, /Saved on This computer/);
    assert.match(app, /Demo catalog/);
    const pollLive = app.slice(app.indexOf("function pollWhileLive"), app.indexOf("function paintDesks"));
    assert.match(pollLive, /isDemoCatalog/);
    assert.match(app, /demoAsk/);
    assert.match(app, /Opened unsent mail/);
    assert.match(app, /Ask stays on the laptop/);
    const demoAskFn = app.slice(app.indexOf("function demoAsk"), app.indexOf("function postAsk"));
    assert.doesNotMatch(demoAskFn, /mode:\s*"meeting"/);
    assert.doesNotMatch(demoAskFn, /location\.href/);
    assert.match(app, /revealHomeWindow/);
    assert.match(app, /desk-window-now/);
    assert.match(app, /demoHighlightWalk/);
    assert.match(app, /revealHomeWindow\("live-meeting"\)/);
    assert.match(app, /Opened Live answer. Never sent/);
    assert.match(app, /Never a cheater overlay/);
    assert.match(app, /if \(onTeach\) speakTeachCue/);
    assert.match(app, /Last step/);
    assert.match(app, /\. Last step/);
    assert.match(app, /showMeeting = !onTeach/);
    assert.match(app, /onTeach/);
    assert.match(app, /Then: /);
    assert.match(app, /Last step/);
    assert.match(app, /canWalk = onTeach &&/);
    assert.match(app, /demoWalkOn/);
    assert.match(app, /canBack/);
    assert.match(app, /openDemoArtifact\("live-meeting"\)/);
    assert.match(app, /meeting-card-kicker/);
    assert.match(app, /meeting-card-captions/);
    assert.match(app, /meetingCopyText/);
    assert.match(app, /isDemoCatalog\(\) && demoInboxSaved\(\)/);
    const cssText = fs.readFileSync(path.join(HOST, "style.css"), "utf8");
    assert.match(cssText, /56vh/);
    assert.match(app, /demoAskChips/);
    assert.match(app, /host-ask-chips/);
    assert.match(app, /Draft email/);
    const chipsFn = app.slice(app.indexOf("function demoAskChips"), app.indexOf("function demoAsk("));
    assert.doesNotMatch(chipsFn, /Send mail|Approve/);
    assert.match(cssText, /#host-ask-chips/);
    assert.match(cssText, /teach-map-stroke/);
    assert.match(cssText, /teach-map-ink/);
    assert.match(cssText, /teach-map-cue/);
    assert.match(cssText, /teach-map-mark/);
    assert.match(cssText, /teach-map-rail/);
    assert.match(cssText, /teach-map-rail button/);
    assert.match(cssText, /pointer-events:\s*auto/);
    assert.match(cssText, /teach-map-control/);
    assert.match(cssText, /teach-map-screen/);
    assert.match(cssText, /\.teach-map\.draw/);
    assert.match(cssText, /teach-map\.tap/);
    assert.match(cssText, /workspace-catalog/);
    assert.match(cssText, /scroll-margin-top/);
    assert.match(app, /demoFrameTeach/);
    assert.match(app, /Draw a larger BOX \(0\.4%\)/);
    assert.match(app, /Walk is full - 8 boxes/);
    assert.match(app, /Drew a BOX/);
    assert.match(cssText, /min-height: 64vh/);
    assert.match(cssText, /teach-map-key/);
    assert.match(cssText, /teach-map-hint\.add/);
    assert.match(cssText, /teach-now-pulse/);
    assert.match(cssText, /teach-map-box\.now/);
    assert.match(cssText, /meeting-card-say/);
    assert.match(cssText, /meeting-card-kicker/);
    assert.match(cssText, /meeting-card-captions/);
    assert.match(cssText, /meeting-card-also/);
    assert.match(cssText, /meeting-card-avoid/);
    assert.match(cssText, /today-plate-kicker/);
    assert.match(cssText, /work-rail/);
    assert.match(cssText, /work-card-kicker/);
    assert.match(cssText, /work-card-open/);
    assert.match(cssText, /room-dock-tile/);
    assert.match(cssText, /desk-window-open/);
    assert.match(cssText, /session-grid/);
    assert.match(cssText, /session-tile/);
    assert.match(cssText, /session-tile-kind/);
    assert.match(app, /work-card-open/);
    assert.match(cssText, /workspace-open-file/);
    assert.match(cssText, /#artifact-body \.teach-map/);
    assert.match(cssText, /#artifact-body \.meeting-card/);
    assert.match(cssText, /desk-window/);
    assert.match(cssText, /desk-document/);
    assert.match(cssText, /desk-inbox/);
    assert.match(cssText, /desk-window-now/);
    assert.match(app, /workspace-open-file/);
    assert.match(app, /paintOpenFileHero/);
    assert.match(app, /paintOpenFileTabs/);
    assert.match(app, /paintOpenFileBody/);
    assert.match(app, /applyOpenTeach/);
    assert.match(app, /applyOpenMeeting/);
    assert.match(app, /applyOpenDocument/);
    assert.match(app, /applyOpenInbox/);
    assert.match(app, /applyOpenSecurity/);
    assert.match(app, /function applyLiveRoom/);
    const liveRoom = app.slice(app.indexOf("function applyLiveRoom"), app.indexOf("function paintLiveRoom"));
    assert.match(liveRoom, /applyOpenDocument/);
    assert.match(liveRoom, /applyOpenInbox/);
    assert.match(liveRoom, /applyOpenSecurity/);
    assert.doesNotMatch(liveRoom, /el\("pre"\)/);
    assert.match(app, /paintDeskWindow/);
    assert.match(app, /notesPaper/);
    assert.match(app, /notesWindowBody/);
    assert.match(app, /inboxComposeBody/);
    assert.match(app, /desk-window/);
    assert.doesNotMatch(app, /id="inbox-send"|Send mail/);
    assert.match(app, /\/api\/teach/);
    assert.match(app, /\/api\/meeting/);
    assert.match(cssText, /open-file-tabs/);
    assert.match(cssText, /open-file-tab\.open/);
    assert.match(app, /Finished file/);
    assert.match(cssText, /stage \.teach-map/);
    assert.match(cssText, /bottom: 36px/);
    assert.match(app, /They asked/);
    assert.match(app, /Heard:/);
    assert.match(app, /-heard-web/);
    assert.match(app, /Plate:/);
    assert.match(app, /Then:/);
    assert.match(app, /-rest-web/);
    assert.match(app, /paintMeetingChips/);
    assert.match(app, /postMeeting/);
    assert.match(app, /meeting-filed/);
    assert.match(app, /paintTalk/);
    assert.match(app, /paintMeetingCard/);
    assert.match(app, /paintTodayPlate/);
    assert.match(app, /paintInboxCard/);
    assert.match(app, /paintDocumentCard/);
    assert.match(app, /paintSecurityCard/);
    assert.match(app, /paintWorkRail/);
    assert.match(app, /paintStage/);
    assert.match(app, /You:/);
    assert.match(app, /meeting-card-say/);
    assert.match(app, /meeting-card-from/);
    assert.match(app, /today-plate/);
    assert.match(app, /On your plate/);
    assert.match(app, /Don't say:/);
    assert.match(app, /meeting-card-also/);
    assert.match(app, /live-cue-also/);
    assert.match(app, /live-cue-them/);
    assert.match(app, /live-cue-you/);
    assert.match(app, /live-cue-captions/);
    assert.match(app, /Live:/);
    assert.match(app, /teach-brief/);
    assert.match(app, /meeting-talk/);
    assert.doesNotMatch(app, /innerHTML/);
    const meeting = await fetch(new Request("https://host.netie.ai/meeting"));
    assert.strictEqual(meeting.status, 200);
    const meetingText = await meeting.text();
    assert.match(meetingText, /id="meeting-brief"/);
    assert.match(meetingText, /id="meeting-asked-web"/);
    assert.match(meetingText, /id="meeting-heard-web"/);
    assert.match(meetingText, /id="meeting-chips"/);
    assert.match(meetingText, /id="meeting-filed"/);
    assert.match(meetingText, /id="brief-copy"/);
    assert.match(meetingText, /id="cue-copy"/);
    assert.match(meetingText, /id="brief-download"/);
    assert.match(meetingText, /Live meeting answer/);
    assert.match(meetingText, /Live captions/);
    const meetingApi = handlePublicRequest({ method: "GET", pathname: "/api/meeting" });
    assert.strictEqual(JSON.parse(meetingApi.body).localFirst, true);
    assert.strictEqual(JSON.parse(meetingApi.body).exec, false);
    assert.strictEqual(JSON.parse(meetingApi.body).cue, "");
    assert.strictEqual(JSON.parse(meetingApi.body).asked, "");
    assert.strictEqual(JSON.parse(meetingApi.body).heard, "");
    assert.deepStrictEqual(JSON.parse(meetingApi.body).chips, []);
    assert.deepStrictEqual(JSON.parse(meetingApi.body).turns, []);
    const teach = await fetch(new Request("https://host.netie.ai/teach"));
    assert.strictEqual(teach.status, 200);
    const teachText = await teach.text();
    assert.match(teachText, /id="teach-brief"/);
    assert.match(teachText, /id="teach-cue-web"/);
    assert.match(teachText, /id="teach-rest-web"/);
    assert.match(teachText, /id="brief-copy"/);
    assert.match(teachText, /id="brief-download"/);
    assert.match(teachText, /id="teach-next"/);
    assert.match(teachText, /id="teach-back"/);
    assert.match(teachText, /Walk path/);
    assert.match(teachText, /This screen/);
    assert.match(teachText, /This display/);
    const overlay = await fetch(new Request("https://host.netie.ai/overlay"));
    assert.strictEqual(overlay.status, 200);
    const overlayText = await overlay.text();
    assert.match(overlayText, /id="walk-chrome"/);
    assert.match(overlayText, /id="walk-copy"/);
    assert.match(overlayText, /id="walk-acts"/);
    assert.match(overlayText, /id="walk-rail"/);
    assert.match(overlayText, /id="walk-chips"/);
    assert.match(overlayText, /id="walk-ask"/);
    assert.match(overlayText, /id="walk-ask-go"/);
    assert.match(overlayText, /submitWalkAsk/);
    assert.match(overlayText, /closest\("#walk-ask-form"\)/);
    assert.match(overlayText, /Draft email/);
    assert.match(overlayText, /overlayDeskHref/);
    assert.match(overlayText, /Got it/);
    assert.match(overlayText, /Last step/);
    assert.match(overlayText, /demoFrame/);
    assert.match(overlayText, /Type in Email/);
    assert.match(overlayText, /syncInboxType/);
    assert.match(overlayText, /inboxTypedTo \|\| "not sent"/);
    assert.match(overlayText, /inboxSaved/);
    assert.match(overlayText, /Saved on This computer/);
    assert.match(overlayText, /saved on This computer - send is parked/);
    assert.match(overlayText, /saved \? "\/workspace\?id=live-meeting"/);
    assert.match(overlayText, /Opened Live answer. Never sent./);
    assert.match(overlayText, /paint\(\[\]\)/);
    assert.match(overlayText, /next\.hidden = saved/);
    assert.match(overlayText, /saved \? "18%" : "72%"/);
    assert.match(overlayText, /filedEl\.hidden = false/);
    assert.match(overlayText, /else if \(liveAsked\)/);
    assert.match(overlayText, /let liveAsked = false/);
    assert.match(overlayText, /paintLiveChrome\(liveAsked\)/);
    assert.match(overlayText, /id="walk-dock"/);
    assert.match(overlayText, /copy\.id = "walk-dock-copy"/);
    assert.match(overlayText, /copyWalkDock/);
    assert.match(overlayText, /id="walk-stack-copy"/);
    assert.match(overlayText, /copyWalkStack/);
    assert.match(overlayText, /overlayDockSpec\("\/workspace\?id=live-meeting"\)/);
    assert.match(overlayText, /id="walk-asked"/);
    assert.match(overlayText, /id="walk-live"/);
    assert.match(overlayText, /paintLiveChrome/);
    assert.match(overlayText, /if \(saved \|\| wasSaved\) hideWalkDock\(\)/);
    assert.match(overlayText, /html\.demo \.point-face\.field/);
    assert.match(overlayText, /id="walk-desktop"/);
    assert.match(overlayText, /paintWalkDesktop/);
    assert.match(overlayText, /walk-win-inbox/);
    assert.match(overlayText, /This computer - no runtime/);
    assert.match(overlayText, /paintWalkDock/);
    assert.match(overlayText, /Unsent mail/);
    assert.match(overlayText, /not sent/);
    assert.match(overlayText, /They asked/);
    assert.match(overlayText, /Say this/);
    assert.match(overlayText, /Never a cheater overlay/);
    assert.match(overlayText, /spoken \+ "\. Then "/);
    assert.match(overlayText, /spoken \+ "\. Last step"/);
    assert.match(overlayText, /leftPct: 12/);
    assert.match(overlayText, /navigator\.clipboard\.writeText/);
    assert.doesNotMatch(overlayText, /window\.open/);
    assert.doesNotMatch(overlayText, /innerHTML/);
    assert.doesNotMatch(overlayText, /Send mail|Approve/);
    assert.doesNotMatch(overlayText, /clicky-orb|stage-orb|chat-bubble/);
    const teachApi = handlePublicRequest({ method: "GET", pathname: "/api/teach" });
    assert.strictEqual(JSON.parse(teachApi.body).localFirst, true);
    assert.strictEqual(JSON.parse(teachApi.body).exec, false);
    assert.strictEqual(JSON.parse(teachApi.body).desk, "teach");
    assert.strictEqual(JSON.parse(teachApi.body).rest, "");
    assert.deepStrictEqual(JSON.parse(teachApi.body).markers, []);
    assert.deepStrictEqual(JSON.parse(teachApi.body).path, []);
    const security = await fetch(new Request("https://host.netie.ai/security"));
    assert.strictEqual(security.status, 200);
    const securityText = await security.text();
    assert.match(securityText, /id="security-brief"/);
    assert.match(securityText, /id="security-chips"/);
    assert.match(securityText, /id="security-cue-web"/);
    assert.match(securityText, /id="report-download"/);
    assert.match(securityText, /generated review/);
    const securityApi = handlePublicRequest({ method: "GET", pathname: "/api/security" });
    assert.strictEqual(JSON.parse(securityApi.body).localFirst, true);
    assert.strictEqual(JSON.parse(securityApi.body).exec, false);
    assert.strictEqual(JSON.parse(securityApi.body).desk, "security");
    assert.strictEqual(JSON.parse(securityApi.body).cue, "");
    const homeApi = handlePublicRequest({ method: "GET", pathname: "/api/home" });
    const homeBody = JSON.parse(homeApi.body);
    assert.strictEqual(homeBody.localFirst, true);
    assert.strictEqual(homeBody.exec, false);
    assert.strictEqual(homeBody.rooms.security.cue, "");
    assert.strictEqual(homeBody.rooms.teach.desk, "teach");
    assert.strictEqual(homeBody.rooms.teach.advance, false);
    assert.deepStrictEqual(homeBody.rooms.teach.path, []);
    assert.strictEqual(homeBody.rooms.teach.action, "");
    assert.deepStrictEqual(homeBody.rooms.meeting.turns, []);
    assert.deepStrictEqual(homeBody.rooms.meeting.captions, []);
    assert.strictEqual(homeBody.rooms.meeting.notes, false);
    assert.strictEqual(homeBody.rooms.meeting.also, "");
    assert.strictEqual(homeBody.rooms.meeting.avoid, "");
    assert.deepStrictEqual(homeBody.rooms.today.plate, []);
    assert.deepStrictEqual(homeBody.rooms.security.findings, []);
    assert.strictEqual(homeBody.rooms.security.preview, "");
    assert.strictEqual(homeBody.rooms.inbox.preview, "");
    assert.strictEqual(homeBody.rooms.document.preview, "");
    assert.strictEqual(homeBody.rooms.inbox.desk, "inbox");
    assert.strictEqual(homeBody.rooms.document.desk, "document");
    assert.ok(homeBody.session);
    assert.strictEqual(homeBody.session.empty, true);
    assert.strictEqual(homeBody.session.exec, false);
    assert.deepStrictEqual(homeBody.session.files, []);
    const documentPage = await fetch(new Request("https://host.netie.ai/document"));
    assert.strictEqual(documentPage.status, 200);
    const documentHtml = await documentPage.text();
    assert.match(documentHtml, /id="document-brief"/);
    assert.match(documentHtml, /id="document-chips"/);
    assert.match(documentHtml, /id="brief-copy"/);
    assert.match(documentHtml, /id="docx-download"/);
    assert.match(documentHtml, /generated \.docx/);
    const inboxPage = await fetch(new Request("https://host.netie.ai/inbox"));
    assert.strictEqual(inboxPage.status, 200);
    const inboxHtml = await inboxPage.text();
    assert.match(inboxHtml, /id="inbox-brief"/);
    assert.match(inboxHtml, /id="inbox-chips"/);
    assert.match(inboxHtml, /id="inbox-heard-web"/);
    assert.match(inboxHtml, /id="brief-copy"/);
    assert.match(inboxHtml, /id="eml-download"/);
    assert.match(inboxHtml, /generated \.eml/);
    const documentApi = handlePublicRequest({ method: "GET", pathname: "/api/document" });
    assert.strictEqual(JSON.parse(documentApi.body).localFirst, true);
    assert.strictEqual(JSON.parse(documentApi.body).exec, false);
    const docxPublic = handlePublicRequest({ method: "GET", pathname: "/api/document.docx" });
    assert.strictEqual(docxPublic.status, 404);
    assert.strictEqual(JSON.parse(docxPublic.body).exec, false);
    assert.strictEqual(JSON.parse(docxPublic.body).act, false);
    const docxBare = handlePublicRequest({ method: "GET", pathname: "/document.docx" });
    assert.strictEqual(docxBare.status, 404);
    assert.strictEqual(JSON.parse(docxBare.body).act, false);
    const inboxApi = handlePublicRequest({ method: "GET", pathname: "/api/inbox" });
    assert.strictEqual(JSON.parse(inboxApi.body).cue, "");
    const emlPublic = handlePublicRequest({ method: "GET", pathname: "/api/inbox.eml" });
    assert.strictEqual(emlPublic.status, 404);
    assert.strictEqual(JSON.parse(emlPublic.body).send, false);
    assert.strictEqual(JSON.parse(emlPublic.body).act, false);
    const emlBare = handlePublicRequest({ method: "GET", pathname: "/inbox.eml" });
    assert.strictEqual(emlBare.status, 404);
    const reportPublic = handlePublicRequest({ method: "GET", pathname: "/api/security.md" });
    assert.strictEqual(reportPublic.status, 404);
    assert.strictEqual(JSON.parse(reportPublic.body).approve, false);
    assert.strictEqual(JSON.parse(reportPublic.body).act, false);
    const reportBare = handlePublicRequest({ method: "GET", pathname: "/security.md" });
    assert.strictEqual(reportBare.status, 404);
    assert.strictEqual(JSON.parse(reportBare.body).approve, false);
    const packetPublic = handlePublicRequest({ method: "GET", pathname: "/api/session.zip" });
    assert.strictEqual(packetPublic.status, 404);
    assert.strictEqual(JSON.parse(packetPublic.body).exec, false);
    assert.strictEqual(JSON.parse(packetPublic.body).act, false);
    assert.strictEqual(JSON.parse(packetPublic.body).send, false);
    assert.strictEqual(JSON.parse(packetPublic.body).approve, false);
    const packetBare = handlePublicRequest({ method: "GET", pathname: "/session.zip" });
    assert.strictEqual(packetBare.status, 404);
    assert.strictEqual(JSON.parse(packetBare.body).exec, false);
    const css = await fetch(new Request("https://host.netie.ai/style.css"));
    assert.strictEqual(css.status, 200);
    assert.match(css.headers.get("content-type"), /text\/css/);
  });

  await test("public fetch does not traverse host/", async () => {
    const fetch = createPublicFetch(readAsset);
    const res = await fetch(new Request("https://host.netie.ai/../package.json"));
    assert.strictEqual(res.status, 404);
    const mcp = await fetch(new Request("https://host.netie.ai/mcp", { method: "POST", body: "{}" }));
    assert.strictEqual(mcp.status, 404);
    const body = JSON.parse(await (await fetch(new Request("https://host.netie.ai/api/state"))).text());
    assert.strictEqual(body.localFirst, true);
  });

  await test("loopback /api/state stays live and is not the public shell", async () => {
    const c = createCoordinator();
    assert.strictEqual(c.claim("pointer-act", { owner: "pointer-hud", goal: "write hello" }).ok, true);
    const on = await c.listen({ host: "127.0.0.1", port: 0 });
    const port = on.address.port;
    const http = require("http");
    const st = await new Promise((resolve, reject) => {
      http.get({ host: "127.0.0.1", port, path: "/api/state" }, (res) => {
        const chunks = [];
        res.on("data", (d) => chunks.push(d));
        res.on("end", () => resolve(JSON.parse(Buffer.concat(chunks).toString("utf8"))));
      }).on("error", reject);
    });
    assert.ok(!st.localFirst);
    assert.strictEqual(st.lanes["pointer-act"].owner, "pointer-hud");
    await c.close();
  });

  await test("Worker entry uses the public router and does not load MCP", () => {
    const src = fs.readFileSync(path.join(__dirname, "..", "workers", "netie-host.js"), "utf8");
    assert.match(src, /createPublicFetch/);
    assert.doesNotMatch(src, /createCoordinator|createMcpAbi|mcp-abi/);
    const wrangler = fs.readFileSync(path.join(__dirname, "..", "wrangler.jsonc"), "utf8");
    assert.match(wrangler, /"directory": "\.\/host"/);
    assert.match(wrangler, /"main": "workers\/netie-host.js"/);
    assert.match(wrangler, /run_worker_first/);
    const app = fs.readFileSync(path.join(HOST, "app.js"), "utf8");
    assert.match(app, /localFirst/);
    assert.match(app, /paintDesks/);
  });

  console.log(`\n${pass} passed, ${fails.length} failed`);
  process.exit(fails.length ? 1 : 0);
})();
