"use strict";
/**
 * P3-UIA-TARGETING — find a control by asking Windows, not by asking a model.
 *
 * Vision targeting works, but it is the expensive way to answer a question the
 * OS already knows: it costs a round-trip to OpenVault, it needs a screenshot
 * of the user's screen to leave the process, and it returns a guess with no
 * error bars. UI Automation returns the real bounding rectangle of the real
 * control, in about a millisecond, without the screen going anywhere.
 *
 * So UIA is primary and vision is the fallback — for controls UIA cannot see
 * (canvas apps, games, remote desktops, custom-drawn UI), which is a real and
 * permanent category, not a temporary gap.
 *
 * Everything that decides anything is pure and lives here; the PowerShell that
 * talks to the automation tree is generated by `buildProbeScript` and run
 * through an injected runner, so the matching logic is testable without a
 * desktop.
 */

/** Control types worth aiming at. A Pane named "Save" is not the Save button. */
const TARGET_CONTROL_TYPES = Object.freeze([
  "Button", "Edit", "Hyperlink", "CheckBox", "RadioButton", "ComboBox",
  "MenuItem", "ListItem", "TabItem", "Text", "Document", "SplitButton",
]);

/** Bound the tree walk — a Chrome window can expose tens of thousands of nodes. */
const MAX_CANDIDATES = 400;

function normalize(text) {
  return String(text || "")
    .toLowerCase()
    .replace(/[&_]/g, "") // Windows accelerators: "&Save" is "Save"
    .replace(/\s+/g, " ")
    .replace(/[.:…]+$/g, "")
    .trim();
}

/**
 * How well does a candidate's name answer the label we were asked for?
 * Higher is better; 0 means no.
 */
function scoreCandidate(label, candidate) {
  const want = normalize(label);
  const got = normalize(candidate && candidate.name);
  if (!want || !got) return 0;

  let score = 0;
  if (got === want) score = 100;
  else if (got.startsWith(want) || want.startsWith(got)) score = 70;
  else if (got.includes(want)) score = 55;
  else {
    // Token overlap catches "Sign in" vs "Sign In button".
    const wantTokens = want.split(" ").filter(Boolean);
    const gotTokens = new Set(got.split(" ").filter(Boolean));
    const hits = wantTokens.filter((t) => gotTokens.has(t)).length;
    if (!hits) return 0;
    // Full token coverage has to clear the default minScore of 50, or this
    // branch is unreachable and "Sign in" never matches "In, Sign".
    score = 30 + Math.round((hits / wantTokens.length) * 30);
  }

  // An interactive control beats a label that merely contains the same words.
  const type = String((candidate && candidate.controlType) || "");
  if (type === "Text" || type === "Document") score -= 12;
  if (candidate && candidate.enabled === false) score -= 25;
  if (candidate && candidate.offscreen === true) score -= 40;
  return Math.max(0, score);
}

/** Screen-pixel rect → the percentages the driver and the planner both speak. */
function rectToPct(rect, screen) {
  if (!rect || !screen) return null;
  const width = Number(screen.width);
  const height = Number(screen.height);
  if (!(width > 0) || !(height > 0)) return null;

  const x = Number(rect.x) + Number(rect.width) / 2 - (Number(screen.x) || 0);
  const y = Number(rect.y) + Number(rect.height) / 2 - (Number(screen.y) || 0);
  if (!Number.isFinite(x) || !Number.isFinite(y)) return null;

  const xPct = (x / width) * 100;
  const yPct = (y / height) * 100;
  // A control scrolled out of the region is not a target; refusing here is what
  // makes the vision fallback fire instead of clicking an edge.
  if (xPct < 0 || xPct > 100 || yPct < 0 || yPct > 100) return null;
  return { xPct, yPct };
}

/**
 * Screen-pixel rect -> overlay box percents (top-left + size).
 * Fully off-screen boxes are refused so we do not invent an edge highlight.
 */
function rectToBoxPct(rect, screen) {
  if (!rect || !screen) return null;
  const width = Number(screen.width);
  const height = Number(screen.height);
  if (!(width > 0) || !(height > 0)) return null;
  const left = Number(rect.x) - (Number(screen.x) || 0);
  const top = Number(rect.y) - (Number(screen.y) || 0);
  const w = Number(rect.width);
  const h = Number(rect.height);
  if (!(w > 0) || !(h > 0) || !Number.isFinite(left) || !Number.isFinite(top)) return null;
  let leftPct = (left / width) * 100;
  let topPct = (top / height) * 100;
  let wPct = (w / width) * 100;
  let hPct = (h / height) * 100;
  if (leftPct + wPct <= 0 || topPct + hPct <= 0 || leftPct >= 100 || topPct >= 100) return null;
  const right = Math.min(100, leftPct + wPct);
  const bottom = Math.min(100, topPct + hPct);
  leftPct = Math.max(0, leftPct);
  topPct = Math.max(0, topPct);
  wPct = right - leftPct;
  hPct = bottom - topPct;
  if (wPct < 0.4 || hPct < 0.4) return null;
  return { leftPct, topPct, wPct, hPct };
}

/** Smaller is more specific: a Button inside a Pane, not the Pane. */
function area(candidate) {
  const r = candidate && candidate.rect;
  if (!r) return Number.MAX_SAFE_INTEGER;
  const a = Number(r.width) * Number(r.height);
  return Number.isFinite(a) && a > 0 ? a : Number.MAX_SAFE_INTEGER;
}

/**
 * Pick the control a label meant.
 * @returns {{candidate:object, score:number}|null}
 */
function chooseCandidate(label, candidates, opts = {}) {
  const minScore = Number.isFinite(Number(opts.minScore)) ? Number(opts.minScore) : 50;
  let best = null;
  for (const candidate of Array.isArray(candidates) ? candidates : []) {
    if (!candidate || !candidate.rect) continue;
    const score = scoreCandidate(label, candidate);
    if (score < minScore) continue;
    if (!best || score > best.score || (score === best.score && area(candidate) < area(best.candidate))) {
      best = { candidate, score };
    }
  }
  return best;
}

/** Single-quoted PowerShell literal — the label comes from a model, so quote it. */
function psLiteral(text) {
  return `'${String(text || "").replace(/'/g, "''")}'`;
}

/**
 * PowerShell that dumps the foreground window's automation tree as JSON.
 *
 * Scoped to the foreground window on purpose: walking the whole desktop is slow
 * and would happily return a control in a window the user is not looking at.
 */
function buildProbeScript(label, opts = {}) {
  const max = Number(opts.max) || MAX_CANDIDATES;
  const types = (opts.types || TARGET_CONTROL_TYPES).join("','");
  return [
    "$ErrorActionPreference='Stop'",
    "Add-Type -AssemblyName UIAutomationClient,UIAutomationTypes,System.Windows.Forms | Out-Null",
    "Add-Type -Namespace Native -Name Win -MemberDefinition '[DllImport(\"user32.dll\")]public static extern System.IntPtr GetForegroundWindow();' | Out-Null",
    "$h=[Native.Win]::GetForegroundWindow()",
    "if($h -eq [System.IntPtr]::Zero){ '[]'; exit 0 }",
    "$root=[System.Windows.Automation.AutomationElement]::FromHandle($h)",
    "if($root -eq $null){ '[]'; exit 0 }",
    `$want=${psLiteral(label)}`,
    `$types=@('${types}')`,
    "$walker=[System.Windows.Automation.TreeWalker]::ControlViewWalker",
    "$out=New-Object System.Collections.ArrayList",
    "$queue=New-Object System.Collections.Queue",
    "$queue.Enqueue($root) | Out-Null",
    "$seen=0",
    `while($queue.Count -gt 0 -and $seen -lt ${max}){`,
    "  $el=$queue.Dequeue(); $seen++",
    "  try{",
    "    $child=$walker.GetFirstChild($el)",
    "    while($child -ne $null){ $queue.Enqueue($child) | Out-Null; $child=$walker.GetNextSibling($child) }",
    "    $n=$el.Current.Name; $t=$el.Current.ControlType.ProgrammaticName -replace '^ControlType\\.',''",
    "    if($n -and ($types -contains $t)){",
    "      $r=$el.Current.BoundingRectangle",
    "      if($r.Width -gt 0 -and $r.Height -gt 0){",
    "        $out.Add([pscustomobject]@{name=$n;controlType=$t;enabled=$el.Current.IsEnabled;offscreen=$el.Current.IsOffscreen;rect=@{x=$r.X;y=$r.Y;width=$r.Width;height=$r.Height}}) | Out-Null",
    "      }",
    "    }",
    "  } catch {}",
    "}",
    "$out | ConvertTo-Json -Depth 4 -Compress",
  ].join("\n");
}

/**
 * Read the probe output. PowerShell's ConvertTo-Json emits a bare object rather
 * than a one-element array when there is exactly one match — the classic way a
 * "works on my machine" parser breaks on the single-result case.
 */
function parseProbeOutput(stdout) {
  const text = String(stdout || "").trim();
  if (!text) return [];
  try {
    const data = JSON.parse(text);
    const list = Array.isArray(data) ? data : [data];
    return list.filter((c) => c && c.rect && typeof c.name === "string");
  } catch {
    return [];
  }
}

/**
 * Locate a control through UIA.
 *
 * @param {string} label
 * @param {object} opts
 *   run     async (script) => stdout   — injected; no PowerShell in tests
 *   screen  {x,y,width,height} of the display the coords are relative to
 * @returns {Promise<{xPct:number,yPct:number,via:'uia',name:string,score:number}|null>}
 */
async function findControl(label, opts = {}) {
  const clean = String(label || "").trim();
  if (!clean || typeof opts.run !== "function" || !opts.screen) return null;
  let stdout;
  try {
    stdout = await opts.run(buildProbeScript(clean, opts));
  } catch {
    // UIA is the fast path, not the only path — a failure means "ask vision".
    return null;
  }
  const best = chooseCandidate(clean, parseProbeOutput(stdout), opts);
  if (!best) return null;
  const pct = rectToPct(best.candidate.rect, opts.screen);
  if (!pct) return null;
  return { ...pct, via: "uia", name: best.candidate.name, score: best.score };
}

/**
 * Dump the foreground tree. Same probe as findControl, no winner.
 * Inject `run` so Linux tests never spawn PowerShell.
 */
async function listControls(opts = {}) {
  if (typeof opts.run !== "function") return [];
  let stdout;
  try {
    stdout = await opts.run(buildProbeScript(opts.label || ".", opts));
  } catch {
    return [];
  }
  return parseProbeOutput(stdout);
}

/** Overlay cap. A screen full of dots is not teaching. */
const MAX_TEACH_POINTS = 8;

function pointLabel(name) {
  const clean = String(name || "")
    .replace(/[\[\]]/g, " ")
    .replace(/\s+/g, " ")
    .trim()
    .slice(0, 40);
  return clean || "control";
}

function numberedLabel(name, index) {
  const base = pointLabel(name);
  if (!Number.isInteger(index) || index < 0) return base;
  return `${index + 1} ${base}`.slice(0, 40);
}

function formatPointToken(pct, name, index) {
  const x = Math.round(Number(pct.xPct) * 10) / 10;
  const y = Math.round(Number(pct.yPct) * 10) / 10;
  return `[POINT:${x},${y}:${numberedLabel(name, index)}]`;
}

function formatBoxToken(box, name, index) {
  const l = Math.round(Number(box.leftPct) * 10) / 10;
  const t = Math.round(Number(box.topPct) * 10) / 10;
  const w = Math.round(Number(box.wPct) * 10) / 10;
  const h = Math.round(Number(box.hPct) * 10) / 10;
  return `[BOX:${l},${t},${w},${h}:${numberedLabel(name, index)}]`;
}

function interactivity(candidate) {
  const t = String((candidate && candidate.controlType) || "");
  if (t === "Button" || t === "Hyperlink" || t === "MenuItem" || t === "SplitButton") return 0;
  if (
    t === "Edit" ||
    t === "CheckBox" ||
    t === "RadioButton" ||
    t === "ComboBox" ||
    t === "TabItem" ||
    t === "ListItem"
  ) {
    return 1;
  }
  return 2;
}

/** Lower is earlier in a teach walk. Save before Cancel. Never clicks. */
function ctaRank(name) {
  const n = String(name || "")
    .replace(/&/g, "")
    .trim()
    .toLowerCase();
  if (
    /^(save|ok|okay|yes|next|continue|submit|send|done|apply|create|open|start|install|connect)$/.test(n)
  ) {
    return 0;
  }
  if (/^(cancel|close|no|back|skip|dismiss|not now|later)$/.test(n)) return 2;
  return 1;
}

/**
 * Measured POINT tokens from a control tree. Never invents coordinates.
 * Missing rect, missing screen, off-screen, or disabled => skipped.
 */
function pointControls(controls, screen, opts = {}) {
  const maxRaw = Number(opts.max);
  const max = Number.isFinite(maxRaw)
    ? Math.min(MAX_TEACH_POINTS, Math.max(0, Math.floor(maxRaw)))
    : MAX_TEACH_POINTS;
  const want = String(opts.want || "").trim();
  const list = Array.isArray(controls) ? controls : [];
  const out = [];
  const seen = new Set();

  function add(candidate) {
    if (!candidate || out.length >= max) return false;
    if (candidate.enabled === false || candidate.offscreen === true) return false;
    const pct = rectToPct(candidate.rect, screen);
    if (!pct) return false;
    const box = rectToBoxPct(candidate.rect, screen);
    const key = `${pointLabel(candidate.name)}|${Math.round(pct.xPct)}|${Math.round(pct.yPct)}`;
    if (seen.has(key)) return false;
    seen.add(key);
    out.push({
      xPct: pct.xPct,
      yPct: pct.yPct,
      name: candidate.name,
      token: formatPointToken(pct, candidate.name),
      boxToken: box ? formatBoxToken(box, candidate.name) : "",
      leftPct: box ? box.leftPct : undefined,
      topPct: box ? box.topPct : undefined,
      wPct: box ? box.wPct : undefined,
      hPct: box ? box.hPct : undefined,
      via: "uia",
    });
    return true;
  }

  if (want) {
    const best = chooseCandidate(want, list);
    if (best) add(best.candidate);
  }

  const ranked = list.slice().sort((a, b) => {
    const d = interactivity(a) - interactivity(b);
    if (d) return d;
    const c = ctaRank(a && a.name) - ctaRank(b && b.name);
    if (c) return c;
    return area(a) - area(b);
  });
  for (const candidate of ranked) {
    if (out.length >= max) break;
    add(candidate);
  }
  out.forEach((p, i) => {
    p.token = formatPointToken({ xPct: p.xPct, yPct: p.yPct }, p.name, i);
    if (p.boxToken) {
      p.boxToken = formatBoxToken(
        { leftPct: p.leftPct, topPct: p.topPct, wPct: p.wPct, hPct: p.hPct },
        p.name,
        i
      );
    }
  });
  return out;
}

module.exports = {
  TARGET_CONTROL_TYPES,
  MAX_CANDIDATES,
  MAX_TEACH_POINTS,
  normalize,
  scoreCandidate,
  chooseCandidate,
  rectToPct,
  rectToBoxPct,
  psLiteral,
  formatBoxToken,
  buildProbeScript,
  parseProbeOutput,
  findControl,
  listControls,
  pointControls,
  formatPointToken,
  ctaRank,
};
